# Generated by Django 3.1.1 on 2021-06-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20210620_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='comments', to='home_page.PostComments'),
        ),
    ]
