# Generated by Django 3.1.1 on 2021-06-21 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20210620_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_comment',
        ),
    ]
