# Generated by Django 3.1.1 on 2021-06-21 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_auto_20210621_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
