# Generated by Django 3.1.1 on 2021-06-27 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_auto_20210623_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomments',
            options={'ordering': ['comment', 'id']},
        ),
    ]
